# Generated by Django 5.1.4 on 2026-02-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vendor', '0032_alter_vendor_store_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorList',
            fields=[
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendor list',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vendor.vendor_store',),
        ),
    ]
