# Generated by Django 5.1.4 on 2025-07-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subuser',
            field=models.BooleanField(default=False),
        ),
    ]
