# Generated by Django 5.1.4 on 2025-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default=4322),
            preserve_default=False,
        ),
    ]
