# Generated by Django 5.1.4 on 2025-11-08 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
