# Generated by Django 5.1.4 on 2025-12-14 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('masters', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Delete all orphaned Cart records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'Cart').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='vendor.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # Delete all orphaned Favourite records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'Favourite').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='favourite',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='vendor.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # Delete all orphaned FavouriteStore records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'FavouriteStore').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='favouritestore',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourited_store', to='vendor.vendor_store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favouritestore',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # Delete all orphaned Follower records (including duplicates) before adding foreign keys and unique_together
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'Follower').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # Order fields (address, delivery_boy, user) already exist in database - only update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Don't modify database - columns already exist
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='address',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='delivery_boy',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='vendor.deliveryboy'),
                ),
                migrations.AddField(
                    model_name='order',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        # Delete all orphaned OrderItem records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'OrderItem').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendor.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderprintfile',
            name='print_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer.orderprintjob'),
            preserve_default=False,
        ),
        # OrderPrintJob fields that may already exist - only update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Don't modify database - columns/tables may already exist
            state_operations=[
                migrations.AddField(
                    model_name='orderprintjob',
                    name='add_ons',
                    field=models.ManyToManyField(blank=True, related_name='order_print_jobs', to='vendor.addon'),
                ),
                migrations.AddField(
                    model_name='orderprintjob',
                    name='customize_variant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_print_jobs', to='vendor.customizeprintvariant'),
                ),
                migrations.AddField(
                    model_name='orderprintjob',
                    name='print_variant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_print_jobs', to='vendor.printvariant'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='orderprintjob',
            name='order_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='print_job', to='customer.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printfile',
            name='print_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer.printjob'),
            preserve_default=False,
        ),
        # PrintJob fields that may already exist - only update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Don't modify database - columns/tables may already exist
            state_operations=[
                migrations.AddField(
                    model_name='printjob',
                    name='add_ons',
                    field=models.ManyToManyField(blank=True, related_name='print_jobs', to='vendor.addon'),
                ),
                migrations.AddField(
                    model_name='printjob',
                    name='customize_variant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='vendor.customizeprintvariant'),
                ),
                migrations.AddField(
                    model_name='printjob',
                    name='print_variant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='vendor.printvariant'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='printjob',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='print_job', to='customer.cart'),
            preserve_default=False,
        ),
        # Delete all orphaned ProductRequest records with invalid foreign keys before adding constraints
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'ProductRequest').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='productrequest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.product_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrequest',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdfsdsa', to='masters.product_subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # Delete all orphaned ReturnExchange records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'ReturnExchange').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='return_exchanges', to='customer.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='return_exchanges', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # Delete all orphaned Review records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'Review').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='customer.orderitem'),
            preserve_default=False,
        ),
        # Review.user field may already exist - only update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Don't modify database - column may already exist
            state_operations=[
                migrations.AddField(
                    model_name='review',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        # SupportTicket fields that may already exist - only update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Don't modify database - columns may already exist
            state_operations=[
        # Delete all orphaned SupportTicket records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'SupportTicket').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='order',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='customer.order'),
                ),
                migrations.AddField(
                    model_name='supportticket',
                    name='user',
                    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
                ),
            ],
        ),
        # Delete all orphaned TicketMessage records before adding foreign keys
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('customer', 'TicketMessage').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # TicketMessage.ticket field may already exist - only update Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Don't modify database - column may already exist
            state_operations=[
                migrations.AddField(
                    model_name='ticketmessage',
                    name='ticket',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer.supportticket'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='favouritestore',
            unique_together={('user', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follower')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order_item', 'user')},
        ),
    ]
