# Generated by Django 5.1.4 on 2025-06-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_orderitem_description_remove_orderitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
