# Generated by Django 5.1.4 on 2025-12-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
    ]
