# Generated by Django 5.1.4 on 2025-12-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_add_user_id_to_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='photo',
        ),
        migrations.CreateModel(
            name='ProductRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='requests/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='customer.productrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
