# Generated by Django 5.1.4 on 2025-07-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_orderitem_coupon_orderitem_cshback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cshback',
            new_name='cashback',
        ),
    ]
