# Generated by Django 5.1.4 on 2025-12-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_productrequest_photo_productrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_auto_managed',
            field=models.BooleanField(default=False, help_text='Whether the order was automatically managed/assigned by the system'),
        ),
    ]
