# Generated by Django 5.1.4 on 2025-07-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_cshback_orderitem_cashback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cashback',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_total_GST',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_Amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='wallet_amount',
        ),
    ]
