# Generated by Django 5.1.4 on 2026-01-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_is_auto_managed'),
        ('vendor', '0027_saleitem_serial_imei_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='serial_imei_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='vendor.serial_imei_no'),
        ),
    ]
