# Generated by Django 5.1.4 on 2026-01-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_orderitem_serial_imei_number'),
        ('vendor', '0027_saleitem_serial_imei_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.ForeignKey(blank=True, help_text='Coupon applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendor.coupon'),
        ),
    ]
