# Generated by Django 5.1.4 on 2025-08-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_cashback_orderitem_price_and_more'),
        ('vendor', '0109_companyprofile_is_default_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='vendor.deliveryboy'),
        ),
    ]
