# Generated by Django 5.1.4 on 2026-01-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_order_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uengage_rider_contact',
            field=models.CharField(blank=True, help_text='Rider contact number from uEngage webhook', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='uengage_rider_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rider latitude from uEngage webhook', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='uengage_rider_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rider longitude from uEngage webhook', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='uengage_rider_name',
            field=models.CharField(blank=True, help_text='Rider name from uEngage webhook', max_length=100, null=True),
        ),
    ]
