# Generated by Django 5.1.4 on 2026-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_order_uengage_rider_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_accepted', 'Not Accepted'), ('accepted', 'Accepted'), ('ready_to_shipment', 'Ready to Shipment'), ('cancelled', 'Cancelled'), ('cancelled_by_vendor', 'Cancelled by Vendor'), ('completed', 'Completed')], default='not_accepted', max_length=20),
        ),
    ]
