# Generated by Django 5.1.4 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Date/time when order was marked delivered/completed",
            ),
        ),
    ]

