# Generated by Django 5.1.4 on 2025-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('instant_delivery', 'Instant Delivery'), ('general_delivery', 'General Delivery'), ('self_pickup', 'Self Pickup'), ('on_shop_order', 'On-shop Order')], default='self_pickup', max_length=50),
        ),
    ]
