# Generated by Django 5.1.4 on 2026-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_add_return_exchange_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_to_shipment', 'Ready to Shipment'), ('ready_to_deliver', 'Ready to Deliver'), ('intransit', 'In Transit'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('return_ready_to_shipment', 'Return Ready to Shipment'), ('return_in_transit', 'Return In Transit'), ('return_ready_to_deliver', 'Return Ready to Deliver'), ('return_rejected', 'Return Rejected'), ('return_completed', 'Return Completed'), ('return_cancelled', 'Return Cancelled'), ('exchange_requested', 'Exchange Requested'), ('exchange_approved', 'Exchange Approved'), ('exchange_ready_to_shipment', 'Exchange Ready to Shipment'), ('exchange_in_transit', 'Exchange In Transit'), ('exchange_ready_to_deliver', 'Exchange Ready to Deliver'), ('exchange_rejected', 'Exchange Rejected'), ('exchange_completed', 'Exchange Completed'), ('exchange_cancelled', 'Exchange Cancelled'), ('returned/replaced_requested', 'returned/replaced_requested'), ('returned/replaced_approved', 'returned/replaced_approved'), ('returned/replaced_ready_to_shipment', 'returned/replaced_ready_to_shipment'), ('returned/replaced_in_transit', 'returned/replaced_in_transit'), ('returned/replaced_ready_to_deliver', 'returned/replaced_ready_to_deliver'), ('returned/replaced_rejected', 'returned/replaced_rejected'), ('returned/replaced_completed', 'returned/replaced_completed'), ('returned/replaced_cancelled', 'returned/replaced_cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
