# Generated by Django 5.1.4 on 2026-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfile',
            name='file',
            field=models.FileField(upload_to='cart_print_jobs/files/'),
        ),
    ]
