# Generated by Django 5.1.4 on 2026-01-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_printfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfile',
            name='file',
            field=models.FileField(upload_to='print_jobs/files/'),
        ),
    ]
