# Generated by Django 5.1.4 on 2026-01-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_printfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when this item was marked delivered', null=True),
        ),
    ]
