# Generated by Django 5.1.4 on 2026-01-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_add_orderitem_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
