# Generated by Django 5.1.4 on 2025-10-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('page_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('print_type', models.CharField(choices=[('single', 'Single Side'), ('double', 'Both Side')], max_length=20)),
                ('add_ons', models.JSONField(blank=True, default=dict)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_attributes', to='customer.cart')),
            ],
        ),
    ]
