# Generated by Django 5.1.4 on 2025-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_printattributes'),
        ('vendor', '0141_alter_vendor_store_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printattributes',
            name='add_ons',
        ),
        migrations.AddField(
            model_name='printattributes',
            name='add_ons',
            field=models.ManyToManyField(blank=True, related_name='print_attributes_addon', to='vendor.addon'),
        ),
    ]
