# Generated by Django 5.1.4 on 2026-01-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_returnexchange_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_to_shipment', 'Ready to Shipment'), ('ready_to_deliver', 'Ready to Deliver'), ('intransit', 'In Transit'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('return_ready_to_shipment', 'Return Ready to Shipment'), ('return_in_transit', 'Return In Transit'), ('return_rejected', 'Return Rejected'), ('return_completed', 'Return Completed'), ('return_cancelled_by_user', 'Return Cancelled by User'), ('return_picked_up', 'Return Picked Up'), ('exchange_requested', 'Exchange Requested'), ('exchange_approved', 'Exchange Approved'), ('exchange_ready_to_shipment', 'Exchange Ready to Shipment'), ('exchange_in_transit', 'Exchange In Transit'), ('exchange_rejected', 'Exchange Rejected'), ('exchange_completed', 'Exchange Completed'), ('exchange_cancelled_by_user', 'Exchange Cancelled by User'), ('exchange_picked_up', 'Exchange Picked Up'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
