# Generated by Django 5.1.4 on 2025-10-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_printattributes_add_ons_and_more'),
        ('vendor', '0142_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('print_type', models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], default='single', max_length=20)),
                ('add_ons', models.ManyToManyField(blank=True, related_name='print_jobs', to='vendor.addon')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_job', to='customer.cart')),
            ],
        ),
        migrations.CreateModel(
            name='PrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('page_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer.printjob')),
            ],
        ),
        migrations.DeleteModel(
            name='PrintAttributes',
        ),
    ]
