# Generated by Django 5.1.4 on 2025-10-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_printjob_printfile_delete_printattributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='printfile',
            name='file',
            field=models.FileField(default=1, upload_to='print_jobs/files/'),
            preserve_default=False,
        ),
    ]
