# Generated by Django 5.1.4 on 2025-10-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_remove_printfile_file_name_printfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
