# Generated by Django 5.1.4 on 2025-10-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_returnexchange'),
        ('vendor', '0145_vendor_store_is_active_vendor_store_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='customize_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='vendor.customizeprintvariant'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='print_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='vendor.printvariant'),
        ),
    ]
