# Generated by Django 5.1.4 on 2025-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_printjob_customize_variant_printjob_print_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
