# Generated by Django 5.1.4 on 2025-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('returned requested', 'Returned Requested'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnexchange',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('cancled_by_user', 'Cancelled by User'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
