# Generated by Django 5.1.4 on 2025-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_orderitem_status_alter_returnexchange_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('returned requested', 'Returned Requested'), ('replacement requested', 'Replacement Requested'), ('returned completed', 'returned Completed'), ('replacement completed', 'replacement Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=28),
        ),
    ]
