# Generated by Django 5.1.4 on 2025-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnexchange',
            name='status',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('intransit', 'In Transit'), ('delivered', 'Delivered'), ('returned/replaced_requested', 'returned/replaced_requested'), ('returned/replaced_approved', 'returned/replaced_approved'), ('returned/replaced_rejected', 'returned/replaced_rejected'), ('returned/replaced_completed', 'returned/replaced_completed'), ('returned/replaced_cancelled', 'returned/replaced_cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=28),
        ),
    ]
