# Generated by Django 5.1.4 on 2025-10-23 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_productrequest'),
        ('masters', '0043_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product_category'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdfsdsa', to='masters.product_subcategory'),
            preserve_default=False,
        ),
    ]
