# Generated by Django 5.1.4 on 2025-10-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_alter_productrequest_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='customer.orderitem'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
