# Generated by Django 5.1.4 on 2025-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='print_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Side'), ('double', 'Double Side')], default='single', max_length=20, null=True),
        ),
    ]
