# Generated by Django 5.1.4 on 2025-10-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracking_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
