# Generated by Django 5.1.4 on 2025-11-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
