# Generated by Django 5.1.4 on 2025-11-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_order_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
