# Generated by Django 5.1.4 on 2025-11-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_review_is_visible'),
        ('vendor', '0167_companyprofile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('print_type', models.CharField(blank=True, choices=[('single', 'Single Side'), ('double', 'Double Side')], default='single', max_length=20, null=True)),
                ('add_ons', models.ManyToManyField(blank=True, related_name='order_print_jobs', to='vendor.addon')),
                ('customize_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_print_jobs', to='vendor.customizeprintvariant')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_job', to='customer.orderitem')),
                ('print_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_print_jobs', to='vendor.printvariant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_print_jobs/files/')),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('page_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer.orderprintjob')),
            ],
        ),
    ]
