# Generated by Django 5.1.4 on 2025-11-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_orderprintjob_orderprintfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashfree_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cashfree_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cashfree_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
