# Generated by Django 5.1.4 on 2025-12-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_order_cashfree_order_id_order_cashfree_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uengage_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
