# Generated by Django 5.1.4 on 2025-12-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_order_uengage_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
