# Generated by Django 5.1.4 on 2025-12-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_order_tax_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wallet_amount',
        ),
    ]
