# Generated by Django 5.1.4 on 2025-12-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_remove_order_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cashback',
        ),
    ]
