# Generated by Django 5.1.4 on 2025-12-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_remove_order_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_to_deliver', 'Ready to Deliver'), ('intransit', 'In Transit'), ('delivered', 'Delivered'), ('returned/replaced_requested', 'returned/replaced_requested'), ('returned/replaced_approved', 'returned/replaced_approved'), ('returned/replaced_rejected', 'returned/replaced_rejected'), ('returned/replaced_completed', 'returned/replaced_completed'), ('returned/replaced_cancelled', 'returned/replaced_cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=28),
        ),
    ]
