# Generated by Django 5.1.4 on 2025-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery discount applied on shipping fee', max_digits=10),
        ),
    ]
