# Generated by Django 5.1.4 on 2025-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_order_delivery_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_accepted', 'Not Accepted'), ('accepted', 'Accepted'), ('ready_to_shipment', 'Ready to Shipment'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='not_accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_to_shipment', 'Ready to Shipment'), ('ready_to_deliver', 'Ready to Deliver'), ('intransit', 'In Transit'), ('delivered', 'Delivered'), ('returned/replaced_requested', 'returned/replaced_requested'), ('returned/replaced_approved', 'returned/replaced_approved'), ('returned/replaced_rejected', 'returned/replaced_rejected'), ('returned/replaced_completed', 'returned/replaced_completed'), ('returned/replaced_cancelled', 'returned/replaced_cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=28),
        ),
    ]
