# Generated by Django 5.1.4 on 2025-12-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprintjob',
            name='instructions',
        ),
        migrations.AddField(
            model_name='orderprintfile',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
