# Generated by Django 5.1.4 on 2025-12-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_remove_orderprintjob_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='instructions',
        ),
        migrations.AddField(
            model_name='printfile',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
