# Generated by Django 5.1.4 on 2025-04-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_remove_food_menu_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amenity',
        ),
        migrations.DeleteModel(
            name='cat_breed',
        ),
        migrations.DeleteModel(
            name='consultation_type',
        ),
        migrations.DeleteModel(
            name='dog_breed',
        ),
        migrations.DeleteModel(
            name='food_menu',
        ),
        migrations.DeleteModel(
            name='online_consultation_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='service_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='symptom',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='vaccination',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='service_category',
        ),
        migrations.DeleteModel(
            name='service_subcategory',
        ),
    ]
