# Generated by Django 5.1.4 on 2025-04-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='sedrftgyhu', max_length=100),
            preserve_default=False,
        ),
    ]
