# Generated by Django 5.1.4 on 2025-05-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_product_addon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_addon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product_addon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product_addon',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product_addon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product_addon',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product_addon',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product_addon',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.product_addon'),
        ),
        migrations.AddField(
            model_name='product_addon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.product'),
        ),
        migrations.AddField(
            model_name='product_addon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='addons/')),
                ('is_active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product_category')),
            ],
        ),
    ]
