# Generated by Django 5.1.4 on 2025-05-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_remove_product_addon_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_addon',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.addon'),
        ),
    ]
