# Generated by Django 5.1.4 on 2025-05-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_alter_product_addon_addon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='opening_stock',
            new_name='stock',
        ),
    ]
