# Generated by Django 5.1.4 on 2025-05-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_addon',
            name='quantity',
        ),
    ]
