# Generated by Django 5.1.4 on 2025-05-17 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_remove_product_addon_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('boost', models.BooleanField(default=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
            ],
        ),
    ]
