# Generated by Django 5.1.4 on 2025-05-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_companyprofile_user_spotlightproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_addon',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product_addon',
            name='product',
        ),
        migrations.RemoveField(
            model_name='spotlightproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='product',
        ),
        migrations.RemoveField(
            model_name='spotlightproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='addon',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='product_addon',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductSerial',
        ),
        migrations.DeleteModel(
            name='SpotlightProduct',
        ),
    ]
