# Generated by Django 5.1.4 on 2025-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0036_remove_product_addon_addon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
