# Generated by Django 5.1.4 on 2025-05-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0037_expense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
