# Generated by Django 5.1.4 on 2025-05-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0039_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_subcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='product_subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.product_category'),
            preserve_default=False,
        ),
    ]
