# Generated by Django 5.1.4 on 2025-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0040_remove_product_subcategory_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(related_name='main_categories', to='masters.product_category')),
            ],
        ),
    ]
