# Generated by Django 5.1.4 on 2025-10-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0041_maincategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
