# Generated by Django 5.1.4 on 2025-11-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0043_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
