"""
Django settings for syndo project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


import os
from pathlib import Path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4n+lfl+6m7g%z)%y6)*0q@+wu=yl!7xdn#h%+gtymvy!y+-w_v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'masters',
    'customer',
    'vendor',
    'users',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'syndo.urls'

HTML2PDF_API_KEY = 'IjjR93npHaOZ6bXt6BmHdt2AwYRh3LBoe3hIYz0wBkHddGoa79PF00BB9cgPAdVl'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", 
    "http://localhost:8081", # React frontend
    "http://localhost:5173",
    "http://localhost:8082",
]

# CORS settings to allow Authorization header for JWT tokens
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_CREDENTIALS = True


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}

# Ensure a "logs" folder exists in your project root (for local dev)
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s: %(levelname)s: %(message)s"
        },
    },
    "handlers": {
        "request_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            # ✅ Use platform-safe path
            "filename": os.path.join(LOG_DIR, "requests.log"),
            "formatter": "verbose",
        },
        "webhook_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "webhook.log"),
            "formatter": "verbose",
        },
        # Optional console handler (so you also see logs in terminal)
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "customer.views": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "razorpay_webhook": {
            "handlers": ["webhook_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "cashfree_webhook": {
            "handlers": ["webhook_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "vendor.sms_utils": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "vendor.signals": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# # firebase_config.py

# # firebase_config.py
import os
from firebase_admin import credentials, initialize_app

# Firebase Admin SDK setup
firebase_key_path = os.path.join(BASE_DIR, 'syndo', 'svindo-firebase-adminsdk-a8gxo-144e14cdfd.json')
cred = credentials.Certificate(firebase_key_path)
initialize_app(cred)


STREAM_API_KEY = "c7wwttj85hg7"
STREAM_API_SECRET = "cgptvrzsttwj9vcebwy25k7y6aqkd6nxh56gkwxhsj3djs989g7k5wraprep926d"


from datetime import timedelta


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'syndo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True


USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'




STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

AUTH_USER_MODEL = 'users.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File Upload Size Limits
# Increase Django's default upload size limits (default is 2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB - for in-memory uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB - for file uploads
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # Increase if needed



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------
# QuickKYC configuration
# --------------------
# Prefer environment variables; provide defaults suitable for QuickKYC public base URL.
QUICKKYC_BASE_URL = "https://api.quickekyc.com/api/v1"
# Set your API key here (or via environment). Do NOT commit real prod keys.
QUICKKYC_API_KEY = "69cabe8b-255c-4d14-9225-aaad46cd01b6"

# --------------------
# Cashfree configuration (centralized in settings for prod consistency)
# --------------------
# Sandbox credentials provided
CASHFREE_APP_ID = "TEST108865764e007be25d954f99c5e067568801"
CASHFREE_SECRET_KEY = "cfsk_ma_test_f5a5d06b79b70e17a1da4ca3e27daa51_3f74a0da"
# Use sandbox base URL for sandbox keys; switch to https://api.cashfree.com/pg for live keys
CASHFREE_BASE_URL = "https://sandbox.cashfree.com/pg"
# Optional webhook secret if verifying webhooks in prod
# CASHFREE_WEBHOOK_SECRET = "your_webhook_secret"

# --------------------
# uEngage configuration (delivery notifications)
# --------------------
# Fill these with your actual credentials/templates in prod
UENGAGE_API_BASE = os.getenv("UENGAGE_API_BASE", "https://riderapi-staging.uengage.in")  # example base; replace if different
UENGAGE_API_KEY = os.getenv("UENGAGE_API_KEY", "")  # token/key
UENGAGE_WABA = os.getenv("UENGAGE_WABA", "")  # your WhatsApp sender/WABA number/id
# Optional: webhook verification/secret
UENGAGE_WEBHOOK_SECRET = os.getenv("UENGAGE_WEBHOOK_SECRET", "")

# uEngage Flash Rider API (serviceability / create / track / cancel)
UENGAGE_RIDER_BASE = os.getenv("UENGAGE_RIDER_BASE", "https://riderapi-staging.uengage.in")
UENGAGE_ACCESS_TOKEN = os.getenv("UENGAGE_ACCESS_TOKEN", "grdgedhs")  # Test access token

# --------------------
# MSGClub SMS configuration
# --------------------
SMS_API_KEY = os.getenv("SMS_API_KEY", "f2d477bfa9ab62ba439e97d84bd3ba")  # Your MSGClub API key
SMS_API_URL = os.getenv("SMS_API_URL", "msg.msgclub.net")  # SMS API host