"""
Django settings for syndo project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


import os
from pathlib import Path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4n+lfl+6m7g%z)%y6)*0q@+wu=yl!7xdn#h%+gtymvy!y+-w_v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'masters',
    'customer',
    'vendor',
    'users',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'syndo.urls'

HTML2PDF_API_KEY = 'IjjR93npHaOZ6bXt6BmHdt2AwYRh3LBoe3hIYz0wBkHddGoa79PF00BB9cgPAdVl'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", 
    "http://localhost:8081", # React frontend
    "http://localhost:5173",
    "http://localhost:8082",
    "http://www.svindo.com",
    "https://www.svindo.com",
    "https://svindo.com",
]

# CORS settings to allow Authorization header for JWT tokens
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_CREDENTIALS = True


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ]
}

# Ensure a "logs" folder exists in your project root (for local dev)
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s: %(levelname)s: %(message)s"
        },
    },
    "handlers": {
        "request_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            # ✅ Use platform-safe path
            "filename": os.path.join(LOG_DIR, "requests.log"),
            "formatter": "verbose",
        },
        "webhook_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "webhook.log"),
            "formatter": "verbose",
        },
        "signals_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "signals.log"),
            "formatter": "verbose",
        },
        "uengage_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "uengage.log"),
            "formatter": "verbose",
        },
        # Optional console handler (so you also see logs in terminal)
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "customer.views": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "razorpay_webhook": {
            "handlers": ["webhook_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "cashfree_webhook": {
            "handlers": ["webhook_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "vendor.sms_utils": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "vendor.signals": {
            "handlers": ["signals_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "customer.serializers": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "vendor.views": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "integrations.uengage": {
            "handlers": ["uengage_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "uengage_webhook": {
            "handlers": ["uengage_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


# # firebase_config.py

# # firebase_config.py
import os
from firebase_admin import credentials, initialize_app

# Firebase Admin SDK setup
firebase_key_path = os.path.join(BASE_DIR, 'syndo', 'svindo-firebase-adminsdk-a8gxo-144e14cdfd.json')
cred = credentials.Certificate(firebase_key_path)
initialize_app(cred)


STREAM_API_KEY = "e484k6yk9w25"
STREAM_API_SECRET = "vnpzcmbj77np8gr2w2e9ucj6sgmmy3c9939cjrheqj2wat69gckwfjdsesnnqn3k"


from datetime import timedelta


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'syndo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True


USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'




STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

AUTH_USER_MODEL = 'users.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File Upload Size Limits
# Increase Django's default upload size limits (default is 2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB - for in-memory uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB - for file uploads
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # Increase if needed



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------
# QuickKYC configuration
# --------------------
# Prefer environment variables; provide defaults suitable for QuickKYC public base URL.
QUICKKYC_BASE_URL = "https://api.quickekyc.com/api/v1"
# Set your API key here (or via environment). Do NOT commit real prod keys.
QUICKKYC_API_KEY = "69cabe8b-255c-4d14-9225-aaad46cd01b6"

# --------------------
# Cashfree configuration (centralized in settings for prod consistency)
# --------------------
# Sandbox credentials provided
CASHFREE_APP_ID = "CF10886576D5F4BQI17UOS73D3ATCG"
CASHFREE_SECRET_KEY = "cfsk_ma_test_137dc78f51c891e407aa5349544ab7e9_a231a558"
# Use sandbox base URL for sandbox keys; switch to https://api.cashfree.com/pg for live keys
CASHFREE_BASE_URL = "https://sandbox.cashfree.com/pg"
# Optional webhook secret if verifying webhooks in prod
# CASHFREE_WEBHOOK_SECRET = "your_webhook_secret"

# --------------------
# uEngage configuration (delivery notifications)
# --------------------
# Set your actual uEngage credentials here
UENGAGE_API_BASE = "https://open-api.flash.uengage.in"  # Change to production URL if needed
UENGAGE_API_KEY = ""  # Your uEngage API key for notifications/WhatsApp
UENGAGE_WABA = ""  # Your WhatsApp Business Account (WABA) number/ID
# Optional: webhook verification/secret
UENGAGE_WEBHOOK_SECRET = ""  # Webhook secret for verifying uEngage webhooks

# uEngage Flash Rider API (serviceability / create / track / cancel)
# These are required for delivery task creation and serviceability checks
UENGAGE_RIDER_BASE = "https://open-api.flash.uengage.in"  # Change to production URL if needed
UENGAGE_ACCESS_TOKEN = "UEN6960A5AA35B60"  # Your uEngage Rider API access token (currently test token)

# --------------------
# MSGClub SMS configuration
# --------------------
# NOTE: configured directly here (not via env vars), as requested.
SMS_API_KEY = "f2d477bfa9ab62ba439e97d84bd3ba"  # MSGClub API key
SMS_API_URL = "msg.msgclub.net"  # SMS API host
# MSGClub commonly expects the auth param name as AUTH_KEY (not api_key).
SMS_AUTH_PARAM = "AUTH_KEY"
# Default endpoint that worked with HTTPSConnection in this project
SMS_API_ENDPOINT = "rest/services/sendSMS/sendGroupSms"
# MSGClub commonly expects these param names
SMS_MOBILE_PARAM = "mobileNos"
SMS_MESSAGE_PARAM = "message"

# SenderId is required by MSGClub and must be exactly 6 alphabets.
# Replace "SVNDOO" with your approved SenderId from MSGClub panel.
# (Your panel screenshot shows "SVNDO"/Svindo branding; SenderId must be 6 alphabets.)
SMS_SENDER_ID = "SVNDO"

# Parameter name can vary by provider/account; MSGClub commonly uses "senderId"
SMS_SENDER_PARAM = "senderId"

# --------------------
# DLT (template) configuration
# --------------------
# If your MSGClub account is DLT-enforced, delivery may fail unless you pass template identifiers.
# MSGClub sample params commonly used:
# - entityid
# - tmid (principal entity id in some panels)
# - templateid
SMS_ENTITY_ID = ""  # e.g. from MSGClub panel (entityid)
SMS_TM_ID = ""      # e.g. "140200000022" (tmid) if provided
SMS_TEMPLATE_ID_INVOICE = "1707176554643228013"  # templateid (from your panel "Template Info")

# Param names (keep exactly as MSGClub sample)
SMS_ENTITY_PARAM = "entityid"
SMS_TM_PARAM = "tmid"
SMS_TEMPLATE_PARAM = "templateid"

# Route / content type (from your sample API call)
SMS_ROUTE_ID = "1"  # usually "1" for transactional; confirm in MSGClub panel if different
SMS_ROUTE_PARAM = "routeId"
SMS_CONTENT_TYPE = "english"  # e.g. english
SMS_CONTENT_TYPE_PARAM = "smsContentType"

# Optional consent failover id (only if your panel has it)
SMS_CONSENT_FAILOVER_ID = ""  # e.g. "30"
SMS_CONSENT_FAILOVER_PARAM = "concentFailoverId"

# Used to build an invoice link for templates that include a URL variable
# NOTE: must be public domain so customer phones can open it.
SITE_BASE_URL = "https://vendor.svindo.com"

# Customer invoice link (signed token)
# Allows opening invoice PDF without login when a valid token is present.
# 7 days (matches message text: "Valid for 7 days")
CUSTOMER_INVOICE_TOKEN_MAX_AGE_SECONDS = 7 * 24 * 60 * 60